**Домашнє завдання [Модуль 1](https://www.edu.goit.global/uk/learn/8016568/12451952/12451981/training)**

---

1. Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.

In [ ]:
import numpy as np

a = np.arange(1, 11)
print("Вектор з першими 10-ма натуральними числами:", a)

Вектор з першими 10-ма натуральними числами: [ 1  2  3  4  5  6  7  8  9 10]


2. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.

In [ ]:
import numpy as np

A = np.zeros((3, 3), dtype=int)
print(A)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


3. Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.

In [ ]:
import numpy as np

B = np.random.randint(1, 11, size=(5, 5))
print(B)

[[ 3  2  1  4  1]
 [ 9  8  8  9  7]
 [ 4  1  5  5  5]
 [ 1  8  7  1  7]
 [ 5  8  8 10  3]]


4. Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.

In [ ]:
import numpy as np

B = np.random.rand(4, 4)
print(B)

[[0.38945306 0.849978   0.08539156 0.39578892]
 [0.74502654 0.53341389 0.94330116 0.74251748]
 [0.77597746 0.94538843 0.73340494 0.98993891]
 [0.44595493 0.73327153 0.3427759  0.7574825 ]]


5. Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.

In [ ]:
import numpy as np

a = np.random.randint(1, 11, size=(5))
b = np.random.randint(1, 11, size=(5))

print("Результат додавання двох масивів: ", a + b)
print("Результат віднімання двох масивів: ", a - b)
print("Результат множення двох масивів: ", a * b)

Результат додавання двох масивів:  [13  8  4  8 12]
Результат віднімання двох масивів:  [-5  0  2 -4  6]
Результат множення двох масивів:  [36 16  3 12 27]


6. Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.

In [ ]:
import numpy as np

a = np.array([1, 2, 3, 4, 5, 6, 7])
b = np.array([7, 6, 5, 4, 3, 2, 1])

print("Результат склярного добутку векторів a та b: ", np.dot(a, b))


Результат склярного добутку векторів a та b:  84


7. Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.

In [ ]:
import numpy as np

A = np.random.randint(1, 11, size=(2, 2))
B = np.random.randint(1, 11, size=(2, 3))
result =  np.dot(A, B)

print("Результат множення матриць A та B:\n", result)

Результат множення матриць A та B:
 [[100  90  90]
 [ 78  77  75]]


8. Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.

In [ ]:
import numpy as np

A = np.random.randint(1, 11, size=(3, 3))
a_inv = np.linalg.inv(A)

print(a_inv)

[[ 0.23076923 -0.62820513  0.26923077]
 [-0.30769231  0.78205128 -0.19230769]
 [ 0.15384615  0.02564103 -0.15384615]]


9. Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.

In [ ]:
import numpy as np

A = np.random.rand(4, 4)
B = A.T

print(B)

[[0.17714069 0.08710934 0.38378419 0.1051275 ]
 [0.89964767 0.68888659 0.43777866 0.81708074]
 [0.13640194 0.94617281 0.32501967 0.21763684]
 [0.02043765 0.76985925 0.35575871 0.27167775]]


10. Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.

In [ ]:
import numpy as np

A = np.random.randint(1, 11, size=(3, 4))
b = np.random.randint(1, 11, size=4)

result = np.dot(A, b)

print("Результат множення матриці на вектор:\n", result)

Результат множення матриці на вектор:
 [200 179 126]


11. Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.

In [ ]:
import numpy as np

A = np.random.rand(2, 3)
b = np.random.rand(3)

result = np.dot(A, b)

print("Результат множення матриці на вектор:\n", result)

Результат множення матриці на вектор:
 [0.31543234 0.68983853]


12. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.

In [ ]:
import numpy as np

A = np.random.randint(1, 11, size=(2, 2))
B = np.random.randint(1, 11, size=(2, 2))

result = A * B

print("Результат поелементного множення матриць A та B :\n", result)

Результат поелементного множення матриць A та B :
 [[20  5]
 [72  8]]


13. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.

In [ ]:
import numpy as np

A = np.random.randint(1, 11, size=(2, 2))
B = np.random.randint(1, 11, size=(2, 2))

result =np.dot(A, B)

print("Результат добутка матриць A та B :\n", result)

Результат добутка матриць A та B :
 [[46 34]
 [69 50]]


14. Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.

In [ ]:
import numpy as np

A = np.random.randint(1, 101, size=(5, 5))
result = np.sum(A)

print("Сума всіх елементів матриці A :", result)

Сума всіх елементів матриці A : 1188


15. Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.

In [ ]:
import numpy as np

A = np.random.randint(1, 11, size=(4, 4))
B = np.random.randint(1, 11, size=(4, 4))


result = np.subtract(A, B)

print("Різниця матриць A та B: \n", result)

Різниця матриць A та B: 
 [[ 4  3  3  5]
 [-2  2 -2  0]
 [-1  6  5  2]
 [-3  0 -3 -4]]


16. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.

In [ ]:
import numpy as np

B = np.random.rand(3, 3)
result = np.sum(B, axis=1, keepdims=True)

print("\nВектор-стовпчик із сумами елементів кожного рядка матриці B:\n", result)


Вектор-стовпчик із сумами елементів кожного рядка матриці B:
 [[2.21599006]
 [0.76017708]
 [1.04984125]]


17. Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.

In [ ]:
import numpy as np

A = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])

result = np.square(A)

print("\nМатриця з квадратами чисел:\n", result)


Матриця з квадратами чисел:
 [[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]


18. Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.

In [ ]:
import numpy as np

a = np.random.randint(1, 51, size=4)

result = np.sqrt(a)


print("\nВектор з квадратними коренями чисел вектору a:\n", result)



Вектор з квадратними коренями чисел вектору a:
 [3.60555128 5.38516481 6.244998   1.        ]
